version: '3.7'

networks:
  docker_net:
    external: true

services:

  app:
    image: marxlin/jnu-python-node
    container_name: jnuweb
    ports:
      - "3000:3000"
    command: sh -c "yarn config set registry https://registry.npm.taobao.org && yarn install && yarn build && yarn start" 
    working_dir: /app
    volumes:
      - "./docker/app/log:/var/log/jnuHealthCheck"
      - "./:/app"
    networks:
      - docker_net

  database:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: JNUSTU 
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - docker_net
